baseURL ="https://abhinavkuamr.github.io/securityBlogs/"
languageCode = "en-us"
title = "XSS blogs"
theme = "beautifulhugo"
summaryLength = 1

[Params]
  subtitle = ""
  mainSections = ["post"]  # Just use "post" to match directory name
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "illegalFreedom"
  twitter = "https://x.com/_nyxel_"

[[menu.main]]
    name = "About"
    url = "/about/"    # Add leading slash
    weight = 3

[[menu.main]]
    name = "Posts"
    url = "/post/"     # Add leading slash
    weight = 1
